---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/repositories/marshall_database_project
                go build  
                ./marshall_database_project -file=data.csv




